# Generated by Django 5.0.1 on 2024-01-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
