# Generated by Django 4.2.6 on 2024-01-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_baseuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='baseuser',
            table='base_user',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='expense',
            table='expense',
        ),
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
    ]
