# Generated by Django 4.2.6 on 2024-01-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_baseuser_options_alter_baseuser_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='expenses',
            field=models.ManyToManyField(null=True, to='core.expense'),
        ),
    ]
