# Generated by Django 4.2.6 on 2024-01-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_group_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='expenses',
            field=models.ManyToManyField(blank=True, null=True, to='core.expense'),
        ),
    ]
