# Generated by Django 4.2.6 on 2024-01-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_group_group_members_alter_group_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='groups', to='core.expense'),
        ),
    ]
