# Generated by Django 4.2.6 on 2024-01-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, default='https://www.google.com', null=True),
        ),
    ]
